language: python

python:
  - "2.7"

env:
    - FLASK_APP=commands.py

install:
    - pip install -r requirements/common.txt
    # requests is only needed to run the tests
    - pip install requests

notifications:
  email:
    on_success: change
    on_failure: always

services: mongodb

script:
    - cp config.yml.example config.yml
    - cp tests/fake-pubkey.pem /tmp/pubkey.pem
    - flask test
